server:
  port: 8082

mysql:
  host: localhost
  port: 3306
  user: root
  password: 1234
  dbname: go_eco
  maxIdleConns: 10
  maxOpenConns: 100
  connexMaxLifetime: 3600

jwt:
  secret: supersecretkey
