server:
  port: 8082

databases:
  - host: localhost
    port: 3306
    user: root
    password: password
    name: mydb1
  - host: localhost
    port: 3307
    user: dev
    password: devpass
    name: mydb2

jwt:
  secret: supersecretkey
